version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=userpass
      - POSTGRES_DB=test
    volumes:
      - ./docker-volume/pg:/var/lib/postgresql/data
      - ./docker-utils:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped 
  
  mysql:
    image: mysql
    ports: ['3306:3306']
    environment:
      MYSQL_ROOT_PASSWORD: userpass
      MYSQL_USER: admin
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE : testdb
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    restart: unless-stopped
    volumes:
      - ./docker-volume/mysql:/var/lib/mysql

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./docker-volume/mongodb:/data/db
    ports:
      - '27017:27017'