version: '3.9'
services:
  mysql:
    image: mysql
    container_name: mysql_database
    env_file:
       - .env
    ports:
       - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-userpass}
      MYSQL_PASSWORD: ${DB_PASS:-userpass}
      MYSQL_USER:  ${DB_USER:-admin}
      MYSQL_DATABASE : ${DB_NAME:-nodejs_orm}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    restart: unless-stopped
    volumes:
      - ./docker-volume/mysql:/var/lib/mysql